<?php

use App\Http\Middleware\AdminAuthMiddleware;
use App\Http\Middleware\Authenticate;
use App\Http\Middleware\AuthUserMiddleware;
use App\Http\Middleware\BindSubDomainParameter;
use App\Http\Middleware\ClinicMiddleware;
use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__ . '/../routes/web.php',
        commands: __DIR__ . '/../routes/console.php',
        health: '/up',
        then: function () {

            /*
            |--------------------------------------------------------------------------
            | ADMIN DOMAIN
            |--------------------------------------------------------------------------
            */
            Route::domain('admin.localhost')
                ->middleware(['web'])
                ->group(base_path('routes/admin.php'));

            /*
            |--------------------------------------------------------------------------
            | CLINIC SUBDOMAIN
            |--------------------------------------------------------------------------
            */
            Route::domain('{subdomain}.localhost')
                ->middleware(['web', 'clinic'])
                ->group(base_path('routes/clinic.php'));
        }
    )
    ->withMiddleware(function (Middleware $middleware): void {

        $middleware->alias([
            'clinic' => ClinicMiddleware::class,
            'auth' => Authenticate::class,
            'userauth' => AuthUserMiddleware::class,
            'superadminguard' => AdminAuthMiddleware::class,
        ]);

        /*
        |--------------------------------------------------------------------------
        | Bind {subdomain} into every URL generated by route()
        |--------------------------------------------------------------------------
        | Without this, calling route('dashboard') throws:
        |   "Missing required parameter for [Route: dashboard] [Missing parameter: subdomain]"
        |
        | We read the subdomain from the current request host and inject it
        | as a default route parameter so all route() / redirect()->route()
        | calls in clinic views work without passing subdomain manually.
        */
        $middleware->web(append: [
            BindSubDomainParameter::class,
        ]);

    })
    ->withExceptions(function (Exceptions $exceptions): void {
        //
    })->create();
